var namespaceroc_1_1core =
[
    [ "Array", "classroc_1_1core_1_1Array.html", "classroc_1_1core_1_1Array" ],
    [ "Atomic", "classroc_1_1core_1_1Atomic.html", "classroc_1_1core_1_1Atomic" ],
    [ "Buffer", "classroc_1_1core_1_1Buffer.html", "classroc_1_1core_1_1Buffer" ],
    [ "BufferPool", "classroc_1_1core_1_1BufferPool.html", "classroc_1_1core_1_1BufferPool" ],
    [ "Cond", "classroc_1_1core_1_1Cond.html", "classroc_1_1core_1_1Cond" ],
    [ "CrashHandler", "classroc_1_1core_1_1CrashHandler.html", "classroc_1_1core_1_1CrashHandler" ],
    [ "errno_to_str", "classroc_1_1core_1_1errno__to__str.html", "classroc_1_1core_1_1errno__to__str" ],
    [ "HeapAllocator", "classroc_1_1core_1_1HeapAllocator.html", "classroc_1_1core_1_1HeapAllocator" ],
    [ "IAllocator", "classroc_1_1core_1_1IAllocator.html", "classroc_1_1core_1_1IAllocator" ],
    [ "List", "classroc_1_1core_1_1List.html", "classroc_1_1core_1_1List" ],
    [ "ListNode", "classroc_1_1core_1_1ListNode.html", "classroc_1_1core_1_1ListNode" ],
    [ "Logger", "classroc_1_1core_1_1Logger.html", "classroc_1_1core_1_1Logger" ],
    [ "MaxAlign", "unionroc_1_1core_1_1MaxAlign.html", "unionroc_1_1core_1_1MaxAlign" ],
    [ "Mutex", "classroc_1_1core_1_1Mutex.html", "classroc_1_1core_1_1Mutex" ],
    [ "NonCopyable", "classroc_1_1core_1_1NonCopyable.html", "classroc_1_1core_1_1NonCopyable" ],
    [ "NoOwnership", "structroc_1_1core_1_1NoOwnership.html", "structroc_1_1core_1_1NoOwnership" ],
    [ "Pool", "classroc_1_1core_1_1Pool.html", "classroc_1_1core_1_1Pool" ],
    [ "RateLimiter", "classroc_1_1core_1_1RateLimiter.html", "classroc_1_1core_1_1RateLimiter" ],
    [ "RefCnt", "classroc_1_1core_1_1RefCnt.html", "classroc_1_1core_1_1RefCnt" ],
    [ "RefCntOwnership", "structroc_1_1core_1_1RefCntOwnership.html", "structroc_1_1core_1_1RefCntOwnership" ],
    [ "ScopedDestructor", "classroc_1_1core_1_1ScopedDestructor.html", "classroc_1_1core_1_1ScopedDestructor" ],
    [ "ScopedLock", "classroc_1_1core_1_1ScopedLock.html", "classroc_1_1core_1_1ScopedLock" ],
    [ "SharedPtr", "classroc_1_1core_1_1SharedPtr.html", "classroc_1_1core_1_1SharedPtr" ],
    [ "Singleton", "classroc_1_1core_1_1Singleton.html", null ],
    [ "Slice", "classroc_1_1core_1_1Slice.html", "classroc_1_1core_1_1Slice" ],
    [ "TempFile", "classroc_1_1core_1_1TempFile.html", "classroc_1_1core_1_1TempFile" ],
    [ "Thread", "classroc_1_1core_1_1Thread.html", "classroc_1_1core_1_1Thread" ],
    [ "Ticker", "classroc_1_1core_1_1Ticker.html", "classroc_1_1core_1_1Ticker" ],
    [ "UniquePtr", "classroc_1_1core_1_1UniquePtr.html", "classroc_1_1core_1_1UniquePtr" ]
];