var searchData=
[
  ['iallocator_775',['IAllocator',['../classroc_1_1core_1_1IAllocator.html',1,'roc::core']]],
  ['ibackend_776',['IBackend',['../classroc_1_1sndio_1_1IBackend.html',1,'roc::sndio']]],
  ['iblockdecoder_777',['IBlockDecoder',['../classroc_1_1fec_1_1IBlockDecoder.html',1,'roc::fec']]],
  ['iblockencoder_778',['IBlockEncoder',['../classroc_1_1fec_1_1IBlockEncoder.html',1,'roc::fec']]],
  ['iclosehandler_779',['ICloseHandler',['../classroc_1_1netio_1_1ICloseHandler.html',1,'roc::netio']]],
  ['icomposer_780',['IComposer',['../classroc_1_1packet_1_1IComposer.html',1,'roc::packet']]],
  ['iframedecoder_781',['IFrameDecoder',['../classroc_1_1audio_1_1IFrameDecoder.html',1,'roc::audio']]],
  ['iframeencoder_782',['IFrameEncoder',['../classroc_1_1audio_1_1IFrameEncoder.html',1,'roc::audio']]],
  ['interleaver_783',['Interleaver',['../classroc_1_1packet_1_1Interleaver.html',1,'roc::packet']]],
  ['io_5furi_5fto_5fstr_784',['io_uri_to_str',['../classroc_1_1address_1_1io__uri__to__str.html',1,'roc::address']]],
  ['iouri_785',['IoURI',['../structroc_1_1address_1_1IoURI.html',1,'roc::address']]],
  ['iparser_786',['IParser',['../classroc_1_1packet_1_1IParser.html',1,'roc::packet']]],
  ['ireader_787',['IReader',['../classroc_1_1audio_1_1IReader.html',1,'roc::audio::IReader'],['../classroc_1_1packet_1_1IReader.html',1,'roc::packet::IReader']]],
  ['isink_788',['ISink',['../classroc_1_1sndio_1_1ISink.html',1,'roc::sndio']]],
  ['isource_789',['ISource',['../classroc_1_1sndio_1_1ISource.html',1,'roc::sndio']]],
  ['iwriter_790',['IWriter',['../classroc_1_1audio_1_1IWriter.html',1,'roc::audio::IWriter'],['../classroc_1_1packet_1_1IWriter.html',1,'roc::packet::IWriter']]]
];
